<?php

namespace AppBundle\Repository;

/**
 * Commande_JourVisiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Commande_JourVisiteRepository extends \Doctrine\ORM\EntityRepository
{
}
