<?php

namespace AppBundle\Repository;


/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{


    public function calculTotalBilletJour($dateResa)
    {
        return $this->createQueryBuilder('c')
            ->select('SUM(c.nbreBillet)')
            ->where('c.dateReservation = :dateResa')
            ->setParameter('dateResa', $dateResa)
            ->getQuery()
            ->getResult()
            ;
    }



}
