<?php

namespace AppBundle\Repository;

/**
 * jourVisiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jourVisiteRepository extends \Doctrine\ORM\EntityRepository
{
}
