# /src/AppBundle/Resources/config/routing.yml

app_home:
    path: /
    defaults:
        _controller: AppBundle::index


app_ticketing:
    path: /ticketing
    defaults:
        _controller: AppBundle:Ticket:index