# src/AppBundle/Resources/config/services.yml

services:
    app.stock:
        class: AppBundle\Services\VerifStock

    app.limit:
        class: AppBundle\Services\HeureLimit

    app.verifCat:
        class: AppBundle\Services\VerifCategorie

    app.prixCommande:
        class: AppBundle\Services\PrixCommande

    app.paiementStripe:
        class: AppBundle\Services\PaiementStripe